[package]
name = "may05"
version = "0.1.0"
authors = ["Michael Pyle <mpyle101@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grid = "0.13.0"
