[package]
name = "mar14"
version = "0.1.0"
authors = ["Michael Pyle <mpyle101@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.14.0"